title: Persona Modding Docs
description: Documentation and guides for modding Persona Games
theme: just-the-docs
color_scheme: dark

url: https://just-the-docs.github.io

plugins: 
  - jekyll-tabs

aux_links:
  Discord Server: https://discord.gg/naoto  
  Amicitia Wiki: https://amicitia.miraheze.org/wiki/
  GitHub Repository: https://github.com/AnimatedSwine37/persona-modding-docs

callouts:
  warning:
    title: Warning
    color: red
  info: 
    title: Info
    color: blue
  todo:
    title: To Do
    color: yellow