title: Persona Modding Docs
description: Documentation and guides for modding Persona Games
theme: just-the-docs
color_scheme: dark

url: https://just-the-docs.github.io

plugins: 
  - jekyll-tabs

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

callouts:
  warning:
    title: Warning
    color: red
  info: 
    title: Info
    color: blue
  todo:
    title: To Do
    color: yellow