backend:
  name: github
  repo: AnimatedSwine37/persona-modding-docs 
  branch: master
  base_url: http://ec2-13-54-217-203.ap-southeast-2.compute.amazonaws.com

media_folder: "assets/images/uploads"

collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    fields:
      - { name: Title }